backend:
  name: git-gateway
  branch: main
media_folder: "/public/uploads"
public_folder: "/uploads"
collections:
  - name: "fixed_pages"
    label: "Fixed Pages"
    editor:
      preview: false
    create: false
    files:
      - name: "homepage"
        label: "Homepage"
        file: "src/pages/index.md"
        format: "frontmatter"
        fields:
          - label: "Layout"
            name: "layout"
            widget: "select"
            options:
              - { label: "Homepage", value: "../layouts/Index.astro" }
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Banner image", name: "banner_image", widget: "image"}
          - {label: "Banner image alt description", name: "banner_image_alt_description", widget: "string", hint: "A text description of the image. incredibly useful for accessibility — screen readers read this description out to their users so they know what the image means. Alt text is also displayed on the page if the image can't be loaded for some reason: for example, network errors, content blocking, or linkrot."}
          - {label: "Banner heading", name: "banner_heading", widget: "string"}
          - {label: "Content", name: "body", widget: "markdown"}
      - name: "about"
        label: "About"
        file: "src/pages/about.md"
        format: "frontmatter"
        fields:
          - label: "Layout"
            name: "layout"
            widget: "select"
            options:
              - { label: "About", value: "../layouts/About.astro" }
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Left banner image", name: "left_banner_image", widget: "image"}
          - {label: "Left banner image alt description", name: "left_banner_image_alt_description", widget: "string", hint: "A text description of the image. incredibly useful for accessibility — screen readers read this description out to their users so they know what the image means. Alt text is also displayed on the page if the image can't be loaded for some reason: for example, network errors, content blocking, or linkrot."}
          - {label: "Right banner image", name: "right_banner_image", widget: "image"}
          - {label: "Left banner image alt description", name: "right_banner_image_alt_description", widget: "string", hint: "A text description of the image. incredibly useful for accessibility — screen readers read this description out to their users so they know what the image means. Alt text is also displayed on the page if the image can't be loaded for some reason: for example, network errors, content blocking, or linkrot."}
          - {label: "Banner heading", name: "banner_heading", widget: "string"}
          - {label: "Content", name: "body", widget: "markdown"}
      - name: "test-entries-list"
        label: "Test Entries List"
        file: "src/pages/test-entries-list.md"
        format: "frontmatter"
        fields:
          - label: "Layout"
            name: "layout"
            widget: "select"
            options:
              - { label: "Test Entries List", value: "../layouts/TestEntriesList.astro" }
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Banner image", name: "banner_image", widget: "image"}
          - {label: "Banner image alt description", name: "banner_image_alt_description", widget: "string", hint: "A text description of the image. incredibly useful for accessibility — screen readers read this description out to their users so they know what the image means. Alt text is also displayed on the page if the image can't be loaded for some reason: for example, network errors, content blocking, or linkrot."}
          - {label: "No entries message", name: "no_entries_message", widget: "string"}
          - {label: "Content", name: "body", widget: "markdown"}
      - name: "contact"
        label: "Contact"
        file: "src/pages/contact.md"
        format: "frontmatter"
        fields:
          - label: "Layout"
            name: "layout"
            widget: "select"
            options:
              - { label: "Contact", value: "../layouts/Contact.astro" }
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Content", name: "body", widget: "markdown"}
  #
  # Test entries
  #
  - name: "test_entries"
    label: "Test Entries"
    editor:
      preview: false 
    create: true
    extension: ".md"
    format: "frontmatter"
    folder: "src/pages/test-entries/"
    slug: "{{slug}}"
    fields:
      - {label: "Identifier (set only once)", name: "identifier", widget: "string", hint: "URL friendly string containing only alphanumeric characters and hyphens. i.e. 'a-sample-identifier-1'"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Banner image", name: "banner_image", widget: "image"}
      - {label: "Banner image alt description", name: "banner_image_alt_description", widget: "string", hint: "A text description of the image. incredibly useful for accessibility — screen readers read this description out to their users so they know what the image means. Alt text is also displayed on the page if the image can't be loaded for some reason: for example, network errors, content blocking, or linkrot."}
      - {label: "Layout", name: "layout", widget: "hidden", default: "../../layouts/TestEntry.astro"}
      - {label: "Content", name: "body", widget: "markdown"}
  #
  # Blog entries
  #
  - name: "blog_entries"
    label: "Blog Entries"
    editor:
      preview: false 
    create: true
    extension: ".md"
    format: "frontmatter"
    folder: "src/pages/blog-entries/"
    slug: "{{slug}}"
    fields:
      - {label: "Identifier (set only once)", name: "identifier", widget: "string", hint: "URL friendly string containing only alphanumeric characters and hyphens. i.e. 'a-sample-identifier-1'"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Banner image", name: "banner_image", widget: "image"}
      - {label: "Banner image alt description", name: "banner_image_alt_description", widget: "string", hint: "A text description of the image. incredibly useful for accessibility — screen readers read this description out to their users so they know what the image means. Alt text is also displayed on the page if the image can't be loaded for some reason: for example, network errors, content blocking, or linkrot."}
      - {label: "Layout", name: "layout", widget: "hidden", default: "../../layouts/TestEntry.astro"}
      - {label: "Content", name: "body", widget: "markdown"}